name: ui_project_1
description: "First ui project 1"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  freezed_annotation: ^2.4.1
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.4.0

flutter_native_splash:
    color: "#FFFFFF"
    image: assets/images/splash_image.png
    android: true
    ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/


  fonts: 
    - family: CustomFont1
      fonts: 
        - asset: assets/fonts/DancingScript-Regular.ttf
    